const MOVIES_URL = 'https://api.nomoreparties.co/beatfilm-movies';
const MAIN_API_URL = 'https://api.movies-app.nomoredomains.work/api';

const NUMBER_OF_MOVIES_AT_PAGE_AT_BIG_SCREENS = 12;
const NUMBER_OF_MOVIES_AT_PAGE_AT_TABLETS = 8;
const NUMBER_OF_MOVIES_AT_PAGE_AT_PHONES = 5;

const NUMBER_OF_ADDITIONAL_MOVIES_AT_BIG_SCREENS = 3;
const NUMBER_OF_ADDITIONAL_MOVIES_AT_TABLETS = 2;
const NUMBER_OF_ADDITIONAL_MOVIES_AT_PHONES = 2;

const MOVIE_DURATION = (movie) => `${Math.floor(movie.duration / 60)}ч ${movie.duration % 60}м`;

export {MOVIES_URL, MAIN_API_URL, NUMBER_OF_MOVIES_AT_PAGE_AT_BIG_SCREENS, NUMBER_OF_MOVIES_AT_PAGE_AT_TABLETS,
    NUMBER_OF_MOVIES_AT_PAGE_AT_PHONES, NUMBER_OF_ADDITIONAL_MOVIES_AT_BIG_SCREENS, NUMBER_OF_ADDITIONAL_MOVIES_AT_TABLETS,
    NUMBER_OF_ADDITIONAL_MOVIES_AT_PHONES, MOVIE_DURATION};